apiVersion: v1
kind: Namespace
metadata:
  name: webserver2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver2
  namespace: webserver2
  labels:
    app: webserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver2
  template:
    metadata:
      labels:
        app: webserver2
    spec:
      containers:
        - name: webserver2
          image: webserver2:latest # This name and tag is defined in the Tiltfile
          ports:
            - containerPort: 80
          env:
            - name: CLUSTER_NAME
              value: "webserver2"

---
apiVersion: v1
kind: Service
metadata:
  namespace: webserver2
  name: api
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 80
  selector:
    app: webserver2
