apiVersion: v1
kind: Namespace
metadata:
  name: webserver1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver1
  namespace: webserver1
  labels:
    app: webserver1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver1
  template:
    metadata:
      labels:
        app: webserver1
    spec:
      containers:
        - name: webserver1
          image: webserver1:latest # This name and tag is defined in the Tiltfile
          ports:
            - containerPort: 80
          env:
            - name: CLUSTER_NAME
              value: "webserver1"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: webserver1
spec:
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 80
  selector:
    app: webserver1
